language: minimal

install:
- ./scripts/ci/pull-or-build-docker-image.sh

script:
- ./scripts/ci/style-check-and-unit-test.sh

after_script::
- ./scripts/ci/report-coverage.sh

branches:
  only:
    master
